global using BlazingPizza.Data;
global using BlazingPizza.Model;
global using BlazingPizza.Server;
global using BlazingPizza.Services;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.RazorPages;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using System.Diagnostics;